# zshrc
# Evan Wilde
#

export EDITOR='nvim'
export PATH="$PATH:/opt/bin/:$HOME/.local/bin/"
export TZ=':/etc/localtime'

[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color

# Variables
export ARCHFLAGS="-arch x86_64"
ZSH=~/.config/zsh
ANTIGEN=$ZSH/antigen/antigen.zsh
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Include custom completion functions
fpath=($ZSH/completions/ $fpath)

# External configurations
[ -f $ZSH/aliases.zsh ] && . $ZSH/aliases.zsh
[ -f $ZSH/history.zsh ] &&  . $ZSH/history.zsh
[ -f $ZSH/prompt.zsh ] && . $ZSH/prompt.zsh

autoload -U compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# Vim keybindings
bindkey -v

# Library Variables
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/lib/:/opt/lib/cuda:/opt/lib/cuddn"
export CUDA_HOME="/opt/src/cuda/"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
