# zshrc
# Evan Wilde
#

# check if a program exists in the user's path
prog_exists() {
        if hash $1 2>/dev/null; then
                return 0
        else
                return 1
        fi
}
export PATH="$HOME/.bin:$HOME/.local/bin:$HOME/.toolchains/usr/bin:$HOME/.cargo/bin:$PATH"
export GOPATH="$HOME/.local/lib/go/"
export TZ='America/Los_Angeles'

if prog_exists 'nvim'; then
        export EDITOR='nvim'
elif prog_exists 'vim'; then
        export EDITOR='vim'
fi

[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color

# Variables
ZSH=~/.config/zsh
ANTIGEN=$ZSH/antigen/antigen.zsh
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Include custom functions
fpath=($ZSH/completions/ $fpath)

# External configurations
[ -f $ZSH/aliases.zsh ] && . $ZSH/aliases.zsh
[ -f $ZSH/history.zsh ] &&  . $ZSH/history.zsh
[ -f $ZSH/prompt.zsh ] && . $ZSH/prompt.zsh
[ -f $ZSH/completions.zsh ] && . $ZSH/completions.zsh
[ -f $ZSH/private.zsh ] && . $ZSH/private.zsh

# Library Variables
export LD_LIBRARY_PATH="$HOME/.local/lib:$HOME/.toolchains/usr/lib:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export SCCACHE_CACHE_SIZE="30G"

# Options
setopt autocd
setopt nobeep
setopt correct
setopt histignoredups
setopt histignorespace
autoload -U edit-command-line

# Vim keybindings
bindkey -v

zle -N edit-command-line
bindkey '^x^e' edit-command-line
bindkey '^r' history-incremental-pattern-search-backward

# Syntax highlighting if available
[[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && . /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
